[2024-11-18T08:30:25.248+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T08:30:25.284+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_fin scheduled__2024-11-18T00:00:00+00:00 [queued]>
[2024-11-18T08:30:25.307+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_fin scheduled__2024-11-18T00:00:00+00:00 [queued]>
[2024-11-18T08:30:25.308+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-18T08:30:25.337+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_fin> on 2024-11-18 00:00:00+00:00
[2024-11-18T08:30:25.357+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=158) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T08:30:25.361+0000] {standard_task_runner.py:72} INFO - Started process 171 to run task
[2024-11-18T08:30:25.362+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_fin', 'scheduled__2024-11-18T00:00:00+00:00', '--job-id', '703', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmphfzcgk0f']
[2024-11-18T08:30:25.365+0000] {standard_task_runner.py:105} INFO - Job 703: Subtask run_API_fin
[2024-11-18T08:30:25.464+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_fin scheduled__2024-11-18T00:00:00+00:00 [running]> on host 12f134266ead
[2024-11-18T08:30:25.638+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_fin' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-18T00:00:00+00:00'
[2024-11-18T08:30:25.642+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T08:30:25.643+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T08:30:25.645+0000] {logging_mixin.py:190} INFO - Current task name:run_API_fin state:running start_date:2024-11-18 08:30:25.286297+00:00
[2024-11-18T08:30:25.646+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-18T08:30:25.649+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T08:30:25.764+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python', 'C:/Users/33672/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI_fin.py']' returned non-zero exit status 2.
[2024-11-18T08:30:25.766+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T08:30:25.793+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T08:30:25.794+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_fin, run_id=scheduled__2024-11-18T00:00:00+00:00, execution_date=20241118T000000, start_date=20241118T083025, end_date=20241118T083025
[2024-11-18T08:30:25.815+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T08:30:25.816+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T08:30:25.817+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-18 08:11:52.646862+00:00
[2024-11-18T08:30:25.818+0000] {logging_mixin.py:190} INFO - Task hostname:12f134266ead operator:PythonOperator
[2024-11-18T08:30:25.864+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T08:30:25.880+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
