[2024-11-12T11:28:54.968+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-12T11:28:55.100+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_news scheduled__2024-11-03T06:00:00+00:00 [queued]>
[2024-11-12T11:28:55.169+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_news scheduled__2024-11-03T06:00:00+00:00 [queued]>
[2024-11-12T11:28:55.182+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-12T11:28:55.277+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_news> on 2024-11-03 06:00:00+00:00
[2024-11-12T11:28:55.331+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=147) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T11:28:55.341+0000] {standard_task_runner.py:72} INFO - Started process 182 to run task
[2024-11-12T11:28:55.352+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_news', 'scheduled__2024-11-03T06:00:00+00:00', '--job-id', '463', '--raw', '--subdir', 'DAGS_FOLDER/insert_data_fin.py', '--cfg-path', '/tmp/tmpc4wad2ua']
[2024-11-12T11:28:55.356+0000] {standard_task_runner.py:105} INFO - Job 463: Subtask run_API_news
[2024-11-12T11:28:55.677+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_news scheduled__2024-11-03T06:00:00+00:00 [running]> on host 97974acde2c9
[2024-11-12T11:28:56.284+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_news' AIRFLOW_CTX_EXECUTION_DATE='2024-11-03T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-03T06:00:00+00:00'
[2024-11-12T11:28:56.289+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-12T11:28:56.290+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-12T11:28:56.292+0000] {logging_mixin.py:190} INFO - Current task name:run_API_news state:running start_date:2024-11-12 11:28:55.106922+00:00
[2024-11-12T11:28:56.293+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-12T11:28:56.294+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-12T11:28:56.458+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python3', '/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI.py']' returned non-zero exit status 2.
[2024-11-12T11:28:56.464+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-12T11:28:56.514+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-12T11:28:56.517+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_news, run_id=scheduled__2024-11-03T06:00:00+00:00, execution_date=20241103T060000, start_date=20241112T112855, end_date=20241112T112856
[2024-11-12T11:28:56.549+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-12T11:28:56.552+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-12T11:28:56.555+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-12 11:26:22.031825+00:00
[2024-11-12T11:28:56.557+0000] {logging_mixin.py:190} INFO - Task hostname:97974acde2c9 operator:PythonOperator
[2024-11-12T11:28:56.633+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-12T11:28:56.706+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-12T11:28:56.715+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
