[2024-11-17T16:33:23.162+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-17T16:33:23.300+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_fin manual__2024-11-17T16:32:27.357044+00:00 [queued]>
[2024-11-17T16:33:23.350+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_fin manual__2024-11-17T16:32:27.357044+00:00 [queued]>
[2024-11-17T16:33:23.352+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-17T16:33:23.501+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_fin> on 2024-11-17 16:32:27.357044+00:00
[2024-11-17T16:33:23.642+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_fin', 'manual__2024-11-17T16:32:27.357044+00:00', '--job-id', '695', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpq9j09i9f']
[2024-11-17T16:33:23.652+0000] {standard_task_runner.py:105} INFO - Job 695: Subtask run_API_fin
[2024-11-17T16:33:23.643+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=379) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-17T16:33:23.654+0000] {standard_task_runner.py:72} INFO - Started process 388 to run task
[2024-11-17T16:33:24.245+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_fin manual__2024-11-17T16:32:27.357044+00:00 [running]> on host a4a76eee4b32
[2024-11-17T16:33:31.674+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_fin' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T16:32:27.357044+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-17T16:32:27.357044+00:00'
[2024-11-17T16:33:31.683+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-17T16:33:31.684+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-17T16:33:31.685+0000] {logging_mixin.py:190} INFO - Current task name:run_API_fin state:running start_date:2024-11-17 16:33:23.304066+00:00
[2024-11-17T16:33:31.687+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-17T16:33:31.688+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-17T16:33:32.065+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python', 'C:/Users/33672/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI_fin.py']' returned non-zero exit status 2.
[2024-11-17T16:33:32.070+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-17T16:33:48.709+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-17T16:33:48.741+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_fin, run_id=manual__2024-11-17T16:32:27.357044+00:00, execution_date=20241117T163227, start_date=20241117T163323, end_date=20241117T163348
[2024-11-17T16:33:48.736+0000] {job.py:229} INFO - Heartbeat recovered after 17.89 seconds
[2024-11-17T16:33:48.913+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-17T16:33:48.919+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-17T16:33:48.927+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-17 16:32:28.622668+00:00
[2024-11-17T16:33:48.931+0000] {logging_mixin.py:190} INFO - Task hostname:a4a76eee4b32 operator:PythonOperator
[2024-11-17T16:33:49.064+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-17T16:33:49.335+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-17T16:33:49.345+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-17T16:33:49.695+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
