[2024-11-16T12:00:09.920+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T12:00:09.940+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_fin scheduled__2024-11-16T06:00:00+00:00 [queued]>
[2024-11-16T12:00:09.951+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_fin scheduled__2024-11-16T06:00:00+00:00 [queued]>
[2024-11-16T12:00:09.952+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-16T12:00:09.970+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_fin> on 2024-11-16 06:00:00+00:00
[2024-11-16T12:00:09.981+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=277) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-16T12:00:09.983+0000] {standard_task_runner.py:72} INFO - Started process 280 to run task
[2024-11-16T12:00:09.984+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_fin', 'scheduled__2024-11-16T06:00:00+00:00', '--job-id', '681', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmph77c5rks']
[2024-11-16T12:00:09.985+0000] {standard_task_runner.py:105} INFO - Job 681: Subtask run_API_fin
[2024-11-16T12:00:10.049+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_fin scheduled__2024-11-16T06:00:00+00:00 [running]> on host c967fb0415e1
[2024-11-16T12:00:10.173+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_fin' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-16T06:00:00+00:00'
[2024-11-16T12:00:10.176+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-16T12:00:10.176+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-16T12:00:10.177+0000] {logging_mixin.py:190} INFO - Current task name:run_API_fin state:running start_date:2024-11-16 12:00:09.941362+00:00
[2024-11-16T12:00:10.178+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-16T12:00:10.179+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T12:00:10.237+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python3', 'C:/Users/33672/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI_fin.py']' returned non-zero exit status 2.
[2024-11-16T12:00:10.238+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-16T12:00:10.262+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T12:00:10.270+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_fin, run_id=scheduled__2024-11-16T06:00:00+00:00, execution_date=20241116T060000, start_date=20241116T120009, end_date=20241116T120010
[2024-11-16T12:00:10.323+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-16T12:00:10.324+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-16T12:00:10.324+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-16 12:00:00.222632+00:00
[2024-11-16T12:00:10.325+0000] {logging_mixin.py:190} INFO - Task hostname:c967fb0415e1 operator:PythonOperator
[2024-11-16T12:00:10.365+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-16T12:00:10.393+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-16T12:00:10.396+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
