[2024-11-16T11:40:10.464+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T11:40:10.541+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_fin scheduled__2024-11-15T18:00:00+00:00 [queued]>
[2024-11-16T11:40:10.610+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_fin scheduled__2024-11-15T18:00:00+00:00 [queued]>
[2024-11-16T11:40:10.612+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-16T11:40:10.726+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_fin> on 2024-11-15 18:00:00+00:00
[2024-11-16T11:40:10.787+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2494) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-16T11:40:10.807+0000] {standard_task_runner.py:72} INFO - Started process 2509 to run task
[2024-11-16T11:40:10.923+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_fin', 'scheduled__2024-11-15T18:00:00+00:00', '--job-id', '672', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpbh76lxzp']
[2024-11-16T11:40:10.929+0000] {standard_task_runner.py:105} INFO - Job 672: Subtask run_API_fin
[2024-11-16T11:40:11.312+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_fin scheduled__2024-11-15T18:00:00+00:00 [running]> on host aa17a4cdcdc6
[2024-11-16T11:40:11.693+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_fin' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-15T18:00:00+00:00'
[2024-11-16T11:40:11.702+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-16T11:40:11.704+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-16T11:40:11.706+0000] {logging_mixin.py:190} INFO - Current task name:run_API_fin state:running start_date:2024-11-16 11:40:10.550052+00:00
[2024-11-16T11:40:11.707+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-16T11:40:11.708+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T11:40:11.857+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python3', 'C:/Users/33672/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI_fin.py']' returned non-zero exit status 2.
[2024-11-16T11:40:11.858+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-16T11:40:12.026+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T11:40:12.028+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_fin, run_id=scheduled__2024-11-15T18:00:00+00:00, execution_date=20241115T180000, start_date=20241116T114010, end_date=20241116T114012
[2024-11-16T11:40:12.088+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-16T11:40:12.089+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-16T11:40:12.097+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-16 11:36:23.565350+00:00
[2024-11-16T11:40:12.104+0000] {logging_mixin.py:190} INFO - Task hostname:aa17a4cdcdc6 operator:PythonOperator
[2024-11-16T11:40:12.182+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-16T11:40:12.284+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
